### PR TITLE
Delete loader.user.js

### PR DESCRIPTION
**Pull request by dbcashx**
how to delete

### CODE REVIEW

**Comment by Piehthyte** [comment]
Who the hell cares? If you don't like it then don't use it but unless anyone asked for your input then please be so kind as to not post.

**Comment by dbcashx** [comment]
me

**Comment by Piehthyte** [comment]
Well if you care so much then find a place to talk about it. Go post on reddit or something! I don't think majority of anyone cares if you want it gone or not. Also, you posting about this doesn't really change anything. If you want it deleted then download it and delete it from your files and boom you just deleted it yourself. Not that hard! :D

**Comment by dbcashx** [comment]
shut the fuck up pussy

**Comment by Piehthyte** [comment]
hahahaha those are big words for a boy! :p no but seriously no need for words to be thrown around just because you don't like something. There is really no need to become so defensive.

**Comment by dbcashx** [comment]
im sorry thanks

**Comment by Drflash55** [comment]
If you want to delete it, then go into TamperMonkey's dashboard, if you're using chrome, and select the loader and bot, and delete them that way...

**Comment by Piehthyte** [comment]
That is another way, yes!

**Comment by dbcashx** [comment]
but every time im on github it says reinstall but it dont let me :0

**Pull request closed without merging**
