### PR TITLE
Slightly improved

### PR DESCRIPTION
**Pull request by stefnotch**
Changed line 857 and got rid of a banana. (Line 127)

### CODE REVIEW

**Comment by Apostolique** [comment]
LOL

**Comment by Apostolique** [comment]
Wait, did you already test this? I think making it loop through only one cell might break it.

**Comment by stefnotch** [comment]
Nope, didn't test it though I doubt that it will break. (Will test it later)

**Comment by henopied** [comment]
It broke i'll give you what my browser said Uncaught TypeError: Cannot read property '0' of undefined right after I split

**Comment by Apostolique** [comment]
To make this work, The launcher needs to be modified too. Right now it loops through all the cells to send directions to the server. (The server only uses the last position sent and uses that for all your cells.)

**Comment by stefnotch** [comment]
Oh, ok! I will fix that and hopefully remember to test my changes before pushing (That's the correct term, right?) them.

**Comment by Apostolique** [comment]
You push, I pull.

**Comment by stefnotch** [comment]
Tested it and works, apparently your code is pretty idiot-proof! If this were Stackoverflow, I would give you a +1! (Actually I couldn't. I don't have enough reputation there! XD)

**Comment by Apostolique** [comment]
I should have explained the whole thing better. And now that I think about it, I should be the one to fix the mess I started.

The code that sends the destinations to the server is here:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L675

The code that lets the player control with the mouse is here:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L265

The code that receives the destinations after the bot logic is here:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L804

Those two variables should now be single variables:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L1349

This here can be made to work on a single variable now instead of an array:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L1812

**Comment by Gjum** [comment]
just a side note: the links above will not work after you push again, because the line numbers will probably change. you should link to a specific commit instead of master:

https://github.com/Apostolique/Agar.io-bot/blob/1b26eec945fffa253f962750dbcff001017cc10b/launcher.user.js#L675
instead of
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L675

**Comment by Apostolique** [comment]
I got lazy :P

**Comment by stefnotch** [comment]
Ok, since this is now fixed, I will close this. :D

**Pull request closed without merging**
