### PR TITLE
Updated Agar.io URL

### PR DESCRIPTION
**Pull request by shaunidiot**
https rendering all the scripts useless.

### CODE REVIEW

**Comment by Drflash55** [comment]
So, this helps with all the scripts being rendered useless?

**Comment by shaunidiot** [comment]
@Drflash55 Most probably. The script wasn't able to detect the non-https URL previously, thus making it unable to work.

**Comment by Drflash55** [comment]
@Apostolique, check to see if this fixes some issues of the bot, and post the results of your findings.
I'm currently at High School right now.

**Comment by ErmiyaEskandary** [comment]
Doesn't this render http useless then as `https://agar.io/*` only works for https, not http ?
Currently working on making this work for https - this is not the way to do it as we need a universal solution which works for **https and http.**

**Pull request closed without merging**
