### PR TITLE
Fix lag

### PR DESCRIPTION
**Pull request by tenten8401**
Was creating an error every time the blob moved and overloading the web browser

### CODE REVIEW

**Comment by henopied** [comment]
Thanks for the fix :D and welcome fellow spigot server owner :P

**Comment by Apostolique** [comment]
This idea for that code is to memorize stuff that gets removed for an extra 3 seconds. I'm surprised there's a problem with it.

**Comment by tenten8401** [comment]
Yea. I removed it on my local copy of the bot and it appears to work fine

**Comment by Apostolique** [comment]
What's the error that you would see?

**Comment by tenten8401** [comment]
The variable you are calling it on is undefined

**Comment by Apostolique** [comment]
If you add:
````
console.log("Time not updated: " + (window.getLastUpdate() - interNodes[element].getUptimeTime()));
````
It doesn't compute a valid number?

**Comment by tenten8401** [comment]
interNodes[element] is aparently undefined. All i know is i removed it on my side, it seems to be working and it isn't lagging.

**Comment by Apostolique** [comment]
interNodes is an object that contains elements. (cell IDs)

We loop through that object using:
````
Object.keys(interNodes).forEach(function(element, index) {
    ....
}
````
I don't think it's possible for interNodes[element] to be undefined.

It's the same as doing:
````
var someArray = [1, 2, 3, 4, 5];
for (var i = 0; i < someArray.length; i++) {
    console.log("The element at index: " + i + " is " + someArray[i]);
}
````
and saying that someArray[i] is undefined.

**Comment by Miguel2706** [comment]
I had the same problem, thanks for the solution!

**Comment by henopied** [comment]
The problem with internodes is it has empty slots because it uses the delete command instead of splicing.

**Comment by Apostolique** [comment]
Oh.

**Comment by henopied** [comment]
Its not nessesarily a problem it just means you gotta use foreach instead of
```
for (var i = 0, var interlen = internodes.length; i < interlen; i++)
```
which is much much faster especially if you cache the length like I showed above

**Pull request closed without merging**
