### PR TITLE
Changed a variable name and improved a few things.

### PR DESCRIPTION
**Pull request by stefnotch**
I improved some trivial things that JSLint likes to complain about... Also, tested it a little bit, it works.
And, I commented out the MAYDAY thing. I still have to change variable u.

P.S. If anything happens not to work, you will get all the complaints! XD

### CODE REVIEW

**Comment by henopied** [comment]
I would recommend using jshint instead of jslint in the future as jslint is getting very opinionated.

**Comment by stefnotch** [comment]
Ok, good to know! (Matter of fact, I wasn't using either of them...I was using JSBin! XD)

**Comment by lautaro1211** [comment]
alguien que hable español envie solicitud de facebook a lautaro jaime foto en blanco y negro asi me ayuda con esto plis

**Comment by stefnotch** [comment]
@lautaro1211 Speak in English please? (Not in Spanish...)

**Pull request merged**
