### PR TITLE
sort all possible threats by enemy distance

### PR DESCRIPTION
**Pull request by henopied**
For later use in prioritizing enemies.

### CODE REVIEW

**Comment by Apostolique** [comment]
There's actually a little catch with this. You don't want to get the distance from their center, but from their closest edge. I drew something to explain better: http://i.imgur.com/IYePDp4.png

If you use the center points, it looks like the green circle is closer to the red circle, but it's actually the blue one that is the closest.

**Comment by henopied** [comment]
what does the structure look like for allposiblethreats?

**Comment by Apostolique** [comment]
In the current version: https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L1852

If you want to look at something that isn't obfuscated: https://github.com/Apostolique/Agar.io-bot/blob/4a177be6a0f210e8bdb0c1888326cda245f13925/launcher.user.js#L1308

Do note that there might be some minor differences in that last one.

**Comment by henopied** [comment]
Ok i fixed it i think :P

**Comment by Apostolique** [comment]
I pulled the changes, but I just noticed, on line 840, it computeDistance should stay as is since it's used to know if someone's split distance.

**Pull request merged**
