### PR TITLE
Added Death Count

### PR DESCRIPTION
**Pull request by DarkN3ss61**
Counts the number of deaths

### CODE REVIEW

**Comment by Apostolique** [comment]
I don't really think it's that useful to show how many deaths happened.

**Comment by DarkN3ss61** [comment]
Why not? then you can leave the bot going and come back in 5 minutes time and go "ahh my bot only dies 3 times"

**Comment by DarkN3ss61** [comment]
+ that other guy wanted it

**Comment by Apostolique** [comment]
I already find the current information that is displayed to be really cluttered. If we're to add more, the interface needs a redesign.

**Comment by DarkN3ss61** [comment]
Well we ain't paying you to sit around here all day and do nothing

**Comment by Apostolique** [comment]
That's right, you ain't paying me.

**Comment by DarkN3ss61** [comment]
*Throws waller at your face*

**Comment by Apostolique** [comment]
Wallet was empty.

**Comment by DarkN3ss61** [comment]
dies a little inside

**Pull request closed without merging**
