### PR TITLE
Corrected blocker issues

### PR DESCRIPTION
**Pull request by FliiFe**
Hi !
I corrected three (potentially) blocking issues on your bot.
The "null test" issue is kinda hard to understand just by reading.
Non compliant code example : http://jsfiddle.net/19z74ncw/
Compliant code example : http://jsfiddle.net/19z74ncw/1/

Hope you'll accept it :-), it's not a big one but an usefull one !

Cordialement (:-D)

### CODE REVIEW

**Comment by Apostolique** [comment]
Oh, I'm surprised I didn't notice the endless loop.

**Comment by FliiFe** [comment]
I have corrected the 'null test' issue, but didn't tested with the new code. I am not convinced by the issue... Is it one on your code ?

**Comment by FliiFe** [comment]
I have noticed an other thing, in your if() statements, you use == or != comparator, but they are originally made to compare types, not content. For example, `' \t\r\n' == 0` will be reported as `true`

**Comment by Apostolique** [comment]
I see. I've tried to avoid Javascript as much as I could just so I wouldn't have to learn that type of stuff. :D

**Comment by FliiFe** [comment]
:smiley: BTW, When will you be streaming ? Soon ?

**Comment by Apostolique** [comment]
Got a couple things to do before.

**Pull request closed without merging**
