### PR TITLE
You will make a bot to generate other bots that run into you?

### PR DESCRIPTION
**Pull request by divan0**
Topic :D also map borders pls :D

### CODE REVIEW

**Comment by dombeef** [comment]
Uh, Im not sure if thats a language barrier issue, but is that a request?

I dont think the main goal of this project is to assist you in playing the game, if you want to "cheat" by having bots slowly feed you, go right ahead, it should be easy to do(like if they see you, have them run towards you), but that is a complete waste of time for anyone else working on this project at this moment in time

And many other forks have map borders enabled, including mine.

**Comment by divan0** [comment]
Sorry, i dont know how to properly use Github yet, i thought i submitted a request! :O

Btw they way the bot helps you right know is called cheating anyway, since it helps you to create patterns to get fed avoiding others. Creating a bot that creates more cells that run into you will make life easier for your main bot too (no waste of time)

Ps: i dont know how to do it :P otherwise i would not have asked :D
PPS: forgive for my english :D

**Comment by dombeef** [comment]
Ah okay, and yeah, a pull request is basically for you to submit code youve fixed/added on to to the main branch, you only suggested on changing the code for things done in the past.

And its probably a fine line for whether this is cheating or not. On one hand its a great example of trying to code for a better algorithm for playing the game(basically allowing you to learn how to code better), although it could also be used for "cheating" the game by having pin point accuracy.

Anyways, I thought I remember hearing that the game developer put in some code so if some person is constantly "feeding" another person, itll eventually kick them from the server, so your idea is not really possible, unless if you want to constantly connect new bots and have them feed you.

**Comment by i9w** [comment]
dombeef, any update on the current state of the bot not working with latest agar.io?

**Comment by dombeef** [comment]
Nope, been busy(and will be for the rest of the day), but all I know is that they updated the agar servers and blocked our bots(No idea how yet, some other scripts do work though) perhaps unintentionally, their main goal was to block the scripts that overlayed their own adsense ads(Honestly, fuck those people who did that, ads are the only source of income for agar.io at the moment).

**Pull request closed without merging**
