### PR TITLE
not even close at all but hey its a start

### PR DESCRIPTION
**Pull request by henopied**
please tell me what you think so far of this effort

### CODE REVIEW

**Comment by Apostolique** [comment]
I think it's cool. Especially if it ends up working.

**Comment by henopied** [comment]
I could use some help by some I mean a lot lol ill work on it tomorrow after school some more

**Comment by henopied** [comment]
BTW this is super old the new stuff is in the gist only.

**Comment by Apostolique** [comment]
I just felt like clicking the button.

**Comment by henopied** [comment]
I could put the new stuff in if you like

**Comment by Apostolique** [comment]
I'm not even sure if it's worth it to maintain my branch.

**Comment by henopied** [comment]
Yea I kinda want it to be in my own repo so I have write access

**Comment by Apostolique** [comment]
Exactly.

**Pull request merged**
