### PR TITLE
Value tuning...

### PR DESCRIPTION
**Pull request by muratlahur**
I've found these values yield better results in real life ..Over-Team-Worked servers (east asia - china) that I play at does muuch better with these settings..

Feel free to try ..

### CODE REVIEW

**Comment by henopied** [comment]
replaced isfood with comparesize that does the same thing? just wondering why

**Comment by muratlahur** [comment]
no it doesn't...is food is set at 1.33 which is should be left at that .. but if you use isfood in threat assessment then you also have to use 1.33 , this way I can define 1.30 (or whatever) for it ..

**Comment by henopied** [comment]
I guess similar was a better word for that I guess better safe than sorry for threat assessment then. (I didn't check all of the context of that change so thats why I got confused)

**Comment by muratlahur** [comment]
my aim in all these is to make the bot survive better against two or more humans teaming up against ..there is no way other than learning neural networks for the bot to understand that ..so with these values I can at least give it a little chance for the "tricks" people seem to favor.

If no one teamed up , these changes will probably be unnecessary but that's far from reality ..

**Comment by muratlahur** [comment]
So just to make it clear for others too . .

With these settings bot will alert for a virus even though it can safely hover above it (disabling someone feeding the bot to eat the virus however)

also it will think people the same size of you are threats (while in reality they are not, with a friend to feed them a few mass they become a threat and bot is in underwater)

It also thinks people greater than 7 times your size (up to 20 indeed) can still be mean enough to split at you ...When teams are spit-flooding the place they just don't care . .

**Comment by muratlahur** [comment]
And oh . .the adjustment in cansplit also works well when assessing threats as someone exactly 2.66 of the bot trying to eat it is a very vague threat due to the same reason I've explained before..So with this value those guys are not threat anymore . ..

**Comment by Apostolique** [comment]
We can try it.

**Pull request merged**
