### PR TITLE
Forgot to increment version number.

### PR DESCRIPTION
**Pull request by DarkN3ss61**
Forgot to increment version number.

### CODE REVIEW

**Comment by Apostolique** [comment]
lol

**Comment by DarkN3ss61** [comment]
Don't "Fine" me mister, GO TO YOUR ROOM!

**Comment by Apostolique** [comment]
I'm glad to hear you say that.

**Comment by DarkN3ss61** [comment]
Was looking at this for about 30 seconds and saying to myself, i don't remember writing this...

**Comment by Apostolique** [comment]
:^)

**Pull request merged**
