### PR TITLE
Do not go to cluster points located at danger points.

### PR DESCRIPTION
**Pull request by lilezek**
Refactor of 710 constant value. 
A quick hack to remove from cluster points of food those who are in radius of danger.

### CODE REVIEW

**Comment by Apostolique** [comment]
The refactor is nice, but the fix you do for ignoring food clusters is wrong. You will need to remove from the array those that too close otherwise you end up with the case where every single food cluster is within danger and then it will have no choice but to pick one of your modified cluster.

**Comment by Gjum** [comment]
Funny that even this PR contains a name change.

**Comment by Apostolique** [comment]
^ Indeed =D But that is just a side effect of a commit he didn't intend to push.

Also, clusters that are behind enemies should also be removed.

**Comment by lilezek** [comment]
@Apostolique yes, I didn't intended to change the name. In the other side, it is faster to ignore some of the clusters than remove them from the array. I'm going to add the code to ignore them so it doesn't break if all clusters are in danger.

**Comment by Apostolique** [comment]
Good question :D

When there is no food and no enemy to run away from, the bot will simply not move. That scenario barely ever happens so I'm keeping it for last.

(Obviously though it will happen more often now that we ignore food. If no enemies are in range and all food is in range of enemies, it will do just that, not move at all.)

**Comment by lilezek** [comment]
I don't know if it only happens on my patch, or its a fault on your code also, that big cells doesn't render themselves as splitable.

**Comment by abalabahaha** [comment]
Some big cells render as obstacles for me using normal bot.

**Comment by Apostolique** [comment]
Right now, if enemies are 10 times bigger, they won't be considered as splitters.

**Comment by chris13524** [comment]
Why???

**Comment by Apostolique** [comment]
Why what? When people are too big, you simply aren't worth it to them.

**Comment by chris13524** [comment]
Oh, right that makes sense, duh

**Comment by chris13524** [comment]
There ought to be a more of a prioritized system instead of "I can go here" and "I can't go here". It should be "I would rather go here rather than there". This could be used in some cases where big balls "area" would be less desirable than places where there aren't ones.

I am not sure if this exists already, but if surrounded (mostly) by balls, it would strafe away from bigger balls because they are "less desirable".

Just a thought though.

**Comment by lilezek** [comment]
@chris13524 I'm here to discuss about this patch, and maybe will do more patches in the future to improve the bot.

@Apostolique If there is any problem with the code of the last push (b80085e) tell me and I'll fix. If not, merge with my fork and I'll continue with the next patch.

**Comment by Apostolique** [comment]
Done.

**Pull request merged**
