### PR TITLE
Tayfa Launcher

### PR DESCRIPTION
**Pull request by badmaan**
Tayfanın !!!

### CODE REVIEW

**Comment by DarkN3ss61** [comment]
Dont steal someone else's bot and claim its your own

**Comment by badmaan** [comment]
I'm don't steal I will share with my group.

**Comment by DarkN3ss61** [comment]
You are asking Apostolique to rename his entire project to your name... you know this isnt going to get approved right?

**Comment by DarkN3ss61** [comment]
Also you are giving no credit at all to Apostolique, you removed his name from every part of the bot, that is stealing

**Pull request closed without merging**
