### PR TITLE
team support and more!

### PR DESCRIPTION
**Pull request by henopied**
mainly add team support but also fixed food ratio based on [this lovely source](http://agar.gcommer.com/index.php?title=Game_Mechanics#Eating) and lastly if your blob even touches the drawcircle for enemies it avoids it (better for later game)
Edit: Don't merge yet, the isitme function does not work with teams (color is undefined.)
Apos if you could please help me understand what I need to do in order to get that function working that would be great (I might figure it out on my own tomorrow while I am more awake but I will not be able to work on this bot much for a week )

### CODE REVIEW

**Comment by Apostolique** [comment]
isItMe should already work for the team mode.

**Comment by henopied** [comment]
What did I do wrong then? oooh nvm it was passing food into the isitme function to let me fix that.

**Comment by Apostolique** [comment]
If it's smaller in size and returns false when put into isItMe, then it's food.

**Comment by henopied** [comment]
Well I have tried a couple times doing different things to no avail (color is not defined when I go to team mode even when I filter out the foods) might you be able to tell me how to avoid this error?

**Pull request closed without merging**
