### PR TITLE
Improved code readability

### PR DESCRIPTION
**Pull request by Timtech**
Testing a first commit to this project

### CODE REVIEW

**Comment by Apostolique** [comment]
I accepted the changes, but those are likely to get completely whipped out next time I fully update the launcher.

**Comment by Timtech** [comment]
Oh, okay. So you have basically already made lots of changes to your local version, eh?

**Comment by Apostolique** [comment]
It's just that the parts that you modified was auto generated code.

**Comment by Parakoopa** [comment]
What generates this code? Wouldn't it be better to have the original source in the repository as well?

**Comment by Apostolique** [comment]
I don't have the original source. If I did have it though, it would indeed be best to edit the original and skip the middle ground obfuscated version.

**Comment by Timtech** [comment]
So is what generates it in the repo somewhere?

**Comment by Parakoopa** [comment]
How can you not have the original source? Is it based on agar.io's source?

**Comment by Apostolique** [comment]
It used to be a file called main_out.js on the agar.io site. Now, it's simply included in a script tag on the main agar.io source page. Perhaps I could contact Zeach for the original version, but I haven't done that yet.

**Comment by Timtech** [comment]
Maybe something from this repo would help you out? https://github.com/123jimin/AgarTools

**Comment by Parakoopa** [comment]
That's a good idea, because I doubt the creator of agar.io is willing to open source parts of the game tbh.

**Comment by Apostolique** [comment]
The client code is already open sourced. It's obfuscated but I've been working around that so far. There already is a non obfuscated version available: http://ac.gcommer.com/ I didn't use that so far because sometimes it stops getting updated for 2 or 3 weeks in a row.

**Comment by Parakoopa** [comment]
Ah, cool! Good to know!

**Comment by Gjum** [comment]
> The client code is already open sourced

I just want to clarify real quick that the "open" in "open source" means more than "everyone can read it". In this case, no free license is applied, and thus it is not "open source".

Sorry for being "that guy", I just want to help prevent misinformation from spreading.

**Comment by Apostolique** [comment]
Actually, the "open source" doesn't mean anything more than simply having the code available. http://www.gnu.org/philosophy/open-source-misses-the-point.en.html

**Pull request merged**
