### PR TITLE
Better-ish wall code and slightly more reasonable split kill avoiding

### PR DESCRIPTION
**Pull request by henopied**

### CODE REVIEW

**Comment by FliiFe** [comment]
What does this improves/add ? It seems to add a lot, but you didn't provide any description.

**Comment by henopied** [comment]
Thanks :)

**Comment by Apostolique** [comment]
I was wonder what's the point of using abs on a Boolean value? I see that on line 540:
````
Math.abs(f.getMapEndY - f.getMapStartY < distanceFromWallY)
````

**Comment by henopied** [comment]
did I do that.. wow I meant it to do abs on f.getMapEndY - f.getMapStartY itself just incase somebody makes a wierd map size

**Pull request merged**
