### PR TITLE
UI Improvements

### PR DESCRIPTION
**Pull request by muratlahur**
I don't know about you guys but I use the bot for actually playing (not sitting and watching pretty lines :P ) and in doing so the more I see the better . .

So in aid of that I've removed "Leaderboard" as it's kinda frikkin obvious :) pulled the alphas down to more comforting level and re-wrote the text around the screen to save more real estate . .Also with the same in mind I've removed the two digits off of the timers (I think timing milliseconds is an overkill :P  )

### CODE REVIEW

**Comment by Apostolique** [comment]
Those don't look like seconds anymore.

**Comment by muratlahur** [comment]
you are absolutely right :) reverted to what it was . .thought by doing so I would get rid of milliseconds but it didn't ...

My desired effect was to have seconds ONLY , no three milliseconds digits following it whis is a wast overkill ..

**Comment by muratlahur** [comment]
Ok , now I got it to look like seconds (and seconds only) .. That before was 6am coding kind of ;)

**Comment by muratlahur** [comment]
ok .. spoke too soon .. now it shows seconds allright but cumulative sum . . 

grr . . .

maybe you should/could  get it to what I want ??

**Comment by muratlahur** [comment]
haha , all I need to do was the uncomment the line above :P 
Now that's giving out JUST the seconds ..perfect..

so here comes my question . .why was that commented out ?

**Comment by Apostolique** [comment]
lol. It was commented out because the old code was more complicated. But you can still use the newer code.

If you look at what you first did:
https://github.com/muratlahur/Agar.io-bot/commit/15aca9a622bffd2058b591df8f2c2e0524f87e73#diff-07964d7e881aff01527bc2acbb3edf74L815

You took the /1000 and changed it to /10. What you should have done was just to strip out the decimals.

The correct line would be:
````
nbSeconds = ((currentDate.getTime() - lifeTimer.getTime())/1000).toFixed(1);
````

**Comment by Linkaan** [comment]
Or simply `nbSeconds = ((currentDate - lifeTimer)/1000).toFixed(1);` would work too.

**Comment by muratlahur** [comment]
No guys, sorry. ..Both of your solution gives one more decimal after the second.  .Which I believe is unnecessary..The original "complicated" code does that .. .

Can anyone achieve that without all the bells and whistles ?

so far sticking out to the original, commented-out , complicated code as I want ONLY seconds

peace

**Comment by Apostolique** [comment]
Why not just use toFixed(0)

**Comment by muratlahur** [comment]
Yes , done that in the new version I just uploaded..Now is perfect..

**Pull request closed without merging**
