### PR TITLE
isItMe and getTeam improved

### PR DESCRIPTION
**Pull request by stefnotch**
Made the 2 slightly faster

### CODE REVIEW

**Comment by henopied** [comment]
Please tab the stuff within the function that you didn't.

**Comment by stefnotch** [comment]
What do you mean? How?

**Comment by Apostolique** [comment]
I'll do it.

**Comment by stefnotch** [comment]
Ok! So, I know most of the stuff I need to know, now off to rewriting half of the code! XD (Ok, it isn't that bad, it's great!)

**Comment by Apostolique** [comment]
lol, I agree a lot of things can be cleaned up.

**Pull request merged**
