### PR TITLE
Suggested method for controlling multiple cells

### PR DESCRIPTION
**Pull request by kakol20**
It takes the average coordinates of where all the cells want go and returns the value of those averages

If it gets stuck (or just stops moving from the average being close to the centre of all the cells) it will return the coordinates where the main cell wants to go instead.

Note: I'm a beginner coder

### CODE REVIEW

**Comment by Drflash55** [comment]
Someone test out this code and see how it works. I would try myself, but I don't know how to do it...

**Comment by Drflash55** [comment]
I found out a way to try it, and as I tested it out, the cell that has negative values seems to be the path the bot favors. So, I'm not sure how this is any different than the current version.

**Comment by kakol20** [comment]
A way to improve code - find the best route to go to instead of using the average

**Comment by Drflash55** [comment]
So this seems more like an enhancement, than a feature...

**Comment by ErmiyaEskandary** [comment]
Tesing...

**Comment by ErmiyaEskandary** [comment]
There is a method to control multiple cells but @Apostolique has disabled it as the single cell control system works better.

**Comment by ErmiyaEskandary** [comment]
The wall code modification has also been done - not merged yet. **All updates first get tested in he `dev` branch and then merged with master.**

**Comment by kakol20** [comment]
Is it better to treat all split cells as one?

**Comment by FliiFe** [comment]
@ErmiyaEskandary Uncommenting it won't make it work. It has been commented out because agar's server don't allow you to control more than one cell.
@kakol20 To answer your question, yes. The bot used to control them indepebdently (back to when it was authorized), ans they each cell would go  in a different direction and never split back

**Comment by ErmiyaEskandary** [comment]
@FliiFe I didn't mean it would work. The code that he has uncommented just doesn't loop through all the cells. What @kakol20 means to is to base the direction of the main cell on all of the cells - not to control them independently.

**Comment by FliiFe** [comment]
@ErmiyaEskandary Uncommenting the code is pointless (I just tested). It tries to control each cell separately, but it can't, so that gives a ridiculous failing bot.

BTW, @Apostolique seem to have his own advice on this :laughing: 
```javascript
//BTW!!! ERROR ERROR ABORT MISSION!!!!!!! READ BELOW -----------
//
//SINCE IT'S STUPID NOW TO ASK EACH CELL WHERE THEY WANT TO GO,
//THE BOT SHOULD SIMPLY PICK ONE AND THAT'S IT, I MEAN WTF....
```

**Comment by muratlahur** [comment]
you can not make it control multiple cells un commenting that code .. That code belongs to the times where agar allowed you to control multiple cells..not anymore..

My bot however , can perfectly control up to 4 cells immaculately.. 

the code however is rather complex (like hundreds of lines) ..

if this project decides to ditch the ADS AND GOOGLE ANALYTICS then I will consider donating that bit of code as well !! 

let's see ..

I repeat, I have the multiple cell code running immaculate already !!

**Comment by FliiFe** [comment]
@muratlahur We are dealing with ads already. See #572

**Comment by muratlahur** [comment]
I mean apos' personal ads that pop up in the middle of the screen and disturb the gameplay until user press E ..

First off that is obtrusive secondly why people need to look at apos personal hobbies just because they want to try the bot ? and most of all , while there are so many people contributing to this project (like me contributing for a while now with absolutely no credits) why the ads directs to apos personal blog ??

The ads should go .. For cleaner sleeker and more fair experience

**Comment by ErmiyaEskandary** [comment]
Ads have been removed and there is no Google Analytics ?!

**Comment by FliiFe** [comment]
@ErmiyaEskandary Not yet.

**Comment by FliiFe** [comment]
@muratlahur See #602

**Comment by muratlahur** [comment]
THERE IS ANALYTICS.. I made an issue about it

**Comment by muratlahur** [comment]
can you also make an issue for the removal of google analytics if I say pretty please ??

if we can also get that out the way I promise I'll just make a pull request with the ENTIRE code of Little Smart Dot ..

That is in effect donating my bot ;)

**Comment by ErmiyaEskandary** [comment]
We don't want all the code for little smart dot ;) @muratlahur 
We want everyone to contribute, just like you are.

**Comment by ErmiyaEskandary** [comment]
@muratlahur See #603

**Comment by muratlahur** [comment]
ermm why ??

**Comment by ErmiyaEskandary** [comment]
> can you also make an issue for the removal of google analytics if I say pretty please ??

**Comment by Drflash55** [comment]
@muratlahur Something about a Live Stream warning... Not sure what this has to do with Google Analytics.

**Comment by ErmiyaEskandary** [comment]
Sorry - @muratlahur make an issue :)

**Comment by muratlahur** [comment]
Ermiya you are losing me .. Why do you not want my entire code again ??

**Comment by Drflash55** [comment]
@muratlahur It's more like a collab effort of sorts. @ErmiyaEskandary doesn't want all of the code to be from just one committer, although your amount of code doesn't even compare to what other collaborators put into this project... So, I'm kinda at even with mura...

**Comment by ErmiyaEskandary** [comment]
@Drflash55 It's based of the current bot code.

**Comment by Drflash55** [comment]
@ErmiyaEskandary And does that raise a conflict?

**Comment by muratlahur** [comment]
man , it's the same bot lol .. I've just added hundreds of lines of code to it .. 

if you want I can put the code's for each extra feature separately into issues like I did and you copy/paste at your own will ..

by the way .. the REAL SELLING POINT of Little Smart Dot is the multiple cell control .. That's what I spent months to get right and it is hundreds of lines of code.. the copy/paste can get a little tedious there

**Comment by ErmiyaEskandary** [comment]
@muratlahur No worries about the copying and pasting but I need to be able to differentiate between new features and they need to be tested thoroughly.

**Comment by Drflash55** [comment]
@muratlahur But the multiple cell control was a removed function of Agar.io

How would you implement a function that was removed from Agar.io entirely, without changing the infrastructure of how Agar.io was built?

**Comment by ErmiyaEskandary** [comment]
@Drflash55 He doesn't mean controlling them individually - he means controlling them all at once if that makes sense

**Comment by Drflash55** [comment]
But, doesn't it do that already? The bot just takes one particular direction of a cell and it goes that way, instead of listening to another cell... If you were to edit it so that it could change it's mind for another cell that want's to go another way, then that would make sense.

**Comment by ErmiyaEskandary** [comment]
But it doesn't account for threats or viruses for the other cells.

**Comment by muratlahur** [comment]
I've kinda hacked it if you don't mind..

I've spent months to come up with an ingenious way..

without showing you the code lemme water your brains by saying this..

Agar allows me to control only blob[0] right ??

fine .. so what I do ?? I calculate threats etc. bad angles. and the obstacle angles for the rest three cells. but instead of applying the angles to them I sum up all the angles and still apply them onto blob[0]


you get the genius ?

so let's say blob[3] is in danger.. then the angles are applied to blob[0] (which we CAN control) and he runs away, in effect pulling the other guy as well

get it ?

**Comment by muratlahur** [comment]
In my code , all four cells are accounted for EVERYTHING..

by the way I've limited to four I can make it upto sixteen as well but already four is QUITE a load on the cpu

**Comment by ErmiyaEskandary** [comment]
You can make issue for your new features but wait until the other issues (twitch,analytics) are solved.

**Comment by muratlahur** [comment]
you bet I'll wait .. That's my whole mission if you didn't realize .. To remove those two from the bot .. 
And I'm (we are) almost at success .. YAY !

**Comment by ErmiyaEskandary** [comment]
@muratlahur I can get on with you ;)

**Comment by muratlahur** [comment]
hold your horses on that ;)

**Comment by ErmiyaEskandary** [comment]
When code is tested, the code will be added and this issue will be closed. How much does it go into a virus for food? Don't want to be sitting there waiting for the bot to get food near the virus . I can use the follow mouse option.

**Comment by muratlahur** [comment]
what ? if you copy pasted my code the bot will NEVER go near a virus to eat.. (it will still go if it's being chased tho)

that's the whole idea, if you are bigger than a virus so that it's a threat . then it will remove all the food in the 5 times the virus diameter around the virus .. 

so for the bot those food don't exist.. it won't even go there

**Comment by ErmiyaEskandary** [comment]
@muratlahur Ah - good idea. Will test in 30 min. Wrong place to be talking about this.

**Comment by FliiFe** [comment]
@muratlahur If you spent months on this, you probably want to get the last commits from this month on your bot. Anyway can you make a PR with your bot ?

**Comment by ErmiyaEskandary** [comment]
@muratlahur @FliiFe was working on this - thanks anyway

**Comment by ErmiyaEskandary** [comment]
@muratlahur NO PR PLEASE

**Comment by ErmiyaEskandary** [comment]
@FliiFe I want all code to go into dev first and then merged into master. Also, we need to test the code. @FliiFe can you add and test the code to see if it doesn't get food near a virus and if it doesn't tell me here and I'll add.

**Comment by muratlahur** [comment]
what's PR ?

**Comment by FliiFe** [comment]
@muratlahur Pull request :)

**Comment by muratlahur** [comment]
and FliiFe , I always monitor all the commits and select if anything useful for me ..

even pull requests from other people and other people's projects..

I monitor everything ;)

and yeah ermiya I will not make a PR

**Comment by ErmiyaEskandary** [comment]
@FliiFe Will you test the code or shall I test it in 20 min ?

**Comment by FliiFe** [comment]
@ErmiyaEskandary I didn't get you on your last request... And, BTW, Pull request can and **should** be made to the `dev` branch, not to the `master` one.

**Comment by ErmiyaEskandary** [comment]
@FliiFe @muratlahur and other people can make PRs to dev to be tested but not for the current code posted here. After these issues are closed, then they can make PRs as it will make conflicts just like this issue.

**Comment by ErmiyaEskandary** [comment]
@muratlahur Could you make a PR for multiple cell control in the dev branch but not for virus and code posted here ? Only multiple cell control

**Pull request closed without merging**
