### PR TITLE
Controls Multiple Cells Again

### PR DESCRIPTION
**Pull request by muratlahur**

### CODE REVIEW

**Comment by Apostolique** [comment]
Why are you adding that back?

**Comment by muratlahur** [comment]
Because it's absolutely necessary.

Without it the bot just ignores the second or third cell . .It feeds them into viruses or other people etc..

It's crucial that it controls the first three cells at least . .

**Comment by muratlahur** [comment]
It is however , needed to be cut down to the first two or three cells , four at max .. anything after that is unnecessary and crazy burden on the cpu ..

But I don't know how to implement that ...Could you ?? if so can you do it on this version I've just edited please ?

**Comment by muratlahur** [comment]
Man I'm testing it now and it's brilliant . ..Please merge this . .in these versions I've deleted the UI improvements so it will look like the way you want . .The updated one of course. .

**Comment by muratlahur** [comment]
Also if it controls just one cell , all the threat assessment etc. is done using that cell, 

assume I've just spit and ate 3-4 cells in one go , I'll have one large and one small cell, and the bot controls the small one, then I'm covered with threats arounds while it's not really so ..

**Comment by muratlahur** [comment]
When controlling multiple cells, when I attack , the attacking cell automatically lock on to the cansplit target making it a sure kill ..

This is absolutely necessary man

**Comment by Apostolique** [comment]
I understand what you mean, but that is not the right code to add back in.

**Comment by muratlahur** [comment]
Well, I'm not a coder at all .. I understand how things work slightly that's it . .All I'm doing is moving things around with the code you provided trying to get things the way I want . .

BTW..right or wrong . .it works right now . .It does control multiple cells..

If you can make it better AND please don't control more than four cells . .That's my (probably others) dream come true

**Comment by muratlahur** [comment]
And yes, I did dig this up from earlier versions.. so what I've added is your code anyway :)

**Comment by Apostolique** [comment]
It's just not the right code.

**Comment by muratlahur** [comment]
And yet it works exactly as needed . .Isn't that amazing :P

**Comment by muratlahur** [comment]
Oh btw I just found out 1.20 for isVirus is still too large and it can hover over viruses ..1.10 is the correct number as at that there is simply no virus it can hover over..it's under the virus or it's a threat..

Can you please update it like that as this also solves the problem of eating food under a virus and exploding as it happens quite often..

**Comment by stefnotch** [comment]
Didn't agar.io break the multiple cells control thing? Also, @Apostolique , mind explaining why it is the wrong code? (Outdated? Not compatible with the current version? Slow? etc?)

Oh, @muratlahur , stop being so impatient. I do realize that this might be totally awesome but give Apostolique a little bit of time.

**Comment by muratlahur** [comment]
multiple cell control thing is the bot being aware of the multiple cells and protecting all of them etc . .
and that is a crucial function also when it's giving out visual data it considers all the cells in equations.. and as with the code above it works perfectly .. now why it is the wrong code, is really low in my priorities list as it just works exactly I want as of now :P

@stefnotch "stop being so impatient" ....I don't like that , I'd like to refrain from personal comments please.I really don't appreciate people telling me what to do ..

**Comment by stefnotch** [comment]
So, it doesn't control the cells separately, it just takes care of all of them? And, about the "stop being so impatient", sorry for judging you by your cover.

**Comment by Drflash55** [comment]
So...
Is this still being worked on, or is it just another forgotten project?

**Comment by muratlahur** [comment]
Hell yeah ;)

flawless,identical control up to 4 cells , organic threat management ,highly advanced organic-bounce wall code, all-new corner code, advanced evasion (purge & split)  mechanics , threat cell count , re-merge and re-unite mechanics ,rapid growth system (split and eat dots super fast early on), split to kill (first two cells for now), and heaps more are currently working brilliantly ...

it's called "Little Smart Dot" now . . .and I don't know what to do with it .. 

but yeah , I've almost maxed out what you can do with it . .. 
muratlahur@hotmail.com if you want a copy of the afore mentioned for yourself ;)

**Comment by ErmiyaEskandary** [comment]
> It's just not the right code.

Reason for closure.

**Pull request closed without merging**
